Complete header
bluehairmylove2014/detoi.vn pull request #12
Opened 2024-01-22 14:27 UTC by rayleigh420

Add some btn to atom CustomButton and use it to complete header ui.

2024-01-22 15:04 UTC, bluehairmylove2014 requested changes

2024-01-22 15:04 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/Header.tsx
> +                <CustomButton style="btn-white-black">
Sao cái này không dùng IconButton, mà dùng CustomButton. IconButton nó viết riêng cho mấy cái nút chỉ có Icon thôi ấy

2024-01-22 15:04 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/Header.tsx
> +    <div className="xl:container">
Tại sao div lại bọc header mà không dùng header bọc div, senmatic sẽ tốt hơn

2024-01-22 15:04 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/Header.tsx
> +                <CustomButton style="btn-white-black">
Sao không dùng thẻ link cho mấy cái navItem này? thẻ link còn có cơ chế prefect nữa, với header.tsx đang là server component, hạn chế dùng button vì sẽ không onClick được

2024-01-22 15:04 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/Header.tsx
> +// 'use client';
header.tsx phải là server component, không dùng client component. Chỉ client cho những component con của nó

2024-01-23 03:07 UTC, rayleigh420 commented on libs/presentational/src/organisms/Header.tsx
> +                <CustomButton style="btn-white-black">
![image](https://github.com/bluehairmylove2014/detoi.vn/assets/72803076/336dd33f-f370-4f9c-8f66-3a172cf879f9)
Tui sẽ dùng vầy nha, chứ option link bên trong CustomerButton nó làm thay đổi css vốn có của button nên tui không dùng type="link"

2024-01-23 09:35 UTC, merged