Feat/validate contact form
bluehairmylove2014/detoi.vn pull request #18
Opened 2024-01-31 16:15 UTC by TanKaka123

2024-02-01 00:47 UTC, bluehairmylove2014 requested changes

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/atoms/Checkbox.tsx
> +  watcher: Boolean;
Boolean => boolean (Kiểu dữ liệu)

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/atoms/Checkbox.tsx
> +  watcher = false,
Đặt defaultValues cho useForm thì watcher tự bằng default, không có set prop default như này

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/atoms/Checkbox.tsx
> +        checked={watcher == true}
Đã register nó cho useForm rồi thì checked sẽ tự true khi value trong form của nó là true, không cần phải gán thế này, dễ gây ra bug

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/atoms/CommonInput.tsx
> +      onFocus={handleInputFocus}
Sao không dùng thuộc tính focus của CSS mà lại viết js để nó giảm performance nhỉ?

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/ContactForm.tsx
> +  const [ isFormError, setIsFormError ] = useState<Boolean>(false);
Boolean => boolean

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/ContactForm.tsx
> +    if (!watch('fullName') || !watch('email') || !watch('topic') || !watch('content')) {
Tạo Yup Schema => Bỏ schema vô useYupValidate.... để tạo resolver => Bỏ resolver vào useForm ngay bên dưới defaultValue là xong, không cần validate thủ công như này, và hạn chế dùng watch, nó hại performance dữ lắm

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/ContactForm.tsx
> +    alert('Submit success');
Gọi useNotification, trong đó có hàm showSuccess và showError, không chơi alert, tui viết hết UI thông báo r

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/ContactForm.tsx
> +  const [ isFormError, setIsFormError ] = useState<Boolean>(false);
Không cần tới state này, xem comment bên dưới cách tạo resolver, trong chỗ cái form onSubmit truyền vô là hàm handleSubmit của useForm, hàm handleSubmit nhận vô 2 tham số, tham số thứ nhất là hàm khi submit form thành công, tham số thứ 2 là submit form thất bại (có lỗi do user chưa nhập như schema)

2024-02-01 00:47 UTC, bluehairmylove2014 commented on libs/presentational/src/organisms/ContactForm.tsx
> +    <form className="max-w-3xl mx-auto w-full h-fit " onSubmit={handleSubmit}>
dùng handleSubmit của useForm, truyền 2 hàm thành công và thất bại vô

2024-02-20 05:10 UTC, bluehairmylove2014 requested changes

2024-02-20 05:10 UTC, bluehairmylove2014 commented on libs/presentational/src/next/organisms/ContactForm.tsx
> +    <form className="max-w-3xl mx-auto w-full h-fit " onSubmit={handleSubmit(onSubmit)}>
Lỗi thì sao, trong useNotification có hàm thông báo riêng cho việc bị lỗi, bỏ nó vô là đc

2024-02-20 05:10 UTC, bluehairmylove2014 commented on package.json
> +    "@hookform/resolvers": "^3.3.4",
Tại sao lại cần cái này??? có useResolver viết riêng rồi mà

2024-02-20 05:10 UTC, bluehairmylove2014 commented on libs/presentational/src/next/organisms/ContactForm.tsx
> +    showSuccess("Submit Success")
Thông báo tiếng Việt

2024-02-20 05:10 UTC, bluehairmylove2014 commented on libs/presentational/src/next/organisms/ContactForm.tsx
> +const schema = yup.object().shape({
Bỏ cái này ra file schema trong util

2024-02-20 05:10 UTC, bluehairmylove2014 commented on libs/presentational/src/next/organisms/ContactForm.tsx
> +  email: yup.string().email('Email không hợp lệ').required('Vui lòng nhập email'),
Mấy cái này có default schema trong util rồi, dùng lại không cần ghi msg từng cái như v

2024-02-20 05:10 UTC, bluehairmylove2014 commented on libs/presentational/src/next/organisms/ContactForm.tsx
> +import { yupResolver } from '@hookform/resolvers/yup';
Dùng useYupValidateResolver có sẵn, không sài thư viện khác

2024-02-20 05:10 UTC, bluehairmylove2014 commented on libs/presentational/src/next/organisms/ContactForm.tsx
> +import useFriendlyCaptcha from '@presentational/atoms/FriendlyCaptcha';
presentation được tách thành native với next rồi, bên web thì sài @present-next thay cho @presentational

2024-02-20 05:10 UTC, bluehairmylove2014 commented on libs/presentational/src/next/atoms/CommonInput.tsx
> +    >
Sao không dùng thuộc tính focus của nó luôn mà phải dùng hàm nhỉ?

2024-02-21 14:07 UTC, TanKaka123 commented on libs/presentational/src/next/organisms/ContactForm.tsx
> +    <form className="max-w-3xl mx-auto w-full h-fit " onSubmit={handleSubmit(onSubmit)}>
đâu cần show error nữa, vì điền không đủ field thì border input change to red color rồi
Còn nếu submit sẽ trigger another action thì sau này sẽ thêm showError sau. Giờ không simulate được

2024-02-22 12:38 UTC, closed without merging