Feat/customer mobile intro page
bluehairmylove2014/detoi.vn pull request #23
Opened 2024-02-20 18:27 UTC by TanKaka123

2024-02-21 05:52 UTC, bluehairmylove2014 requested changes

2024-02-21 05:52 UTC, bluehairmylove2014 commented on apps/customer-mobile/package.json
> +    "react-native-linear-gradient": "*",
đã có sẵn expo-linear-gradient rồi mà thêm cái này làm gì

2024-02-21 05:52 UTC, bluehairmylove2014 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +  PrimaryTitle,
check cách viết của nhánh fe-dev--native

2024-02-21 05:52 UTC, bluehairmylove2014 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +          <SmallParagraph fontWeight="bold">Điều khoản dịch vụ</SmallParagraph>{' '}
Điều khoản dịch vụ đồ phải chuyển hướng tới screen or web chứa nó chứ nhỉ, sao để text bình thường đc

2024-02-21 05:52 UTC, bluehairmylove2014 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +const introSCreenStyle = StyleSheet.create({
tách file riêng, giảm độ dài của file, dễ bảo trì, tìm lỗi, code và quản lý, xem screen home

2024-02-21 05:52 UTC, bluehairmylove2014 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +    width: '100%',
width nếu full màn hình, tham khảo stylesheet của home, có dùng windowWidth

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/styles/spacingConvention.ts
> +const screenVerrizontalPadding = 20;
horizon - vertical

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/organisms/Header.tsx
> +    backgroundColor: '#EEEEEE',
KHông dùng màu tự do không cấu hình, tham khảo màu softBg

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/organisms/Header.tsx
> +      uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/United-kingdom_flag_icon_round.svg/1024px-United-kingdom_flag_icon_round.svg.png',
dùng url thế này xong sau này link die thì sao? Tham khảo các git chuyên làm về flag free-source

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/atoms/text/Title.tsx
> +const PrimaryTitle = ({ children, color }: { children: React.ReactNode, color?: string }) => (
:VVVV PrimaryTitle là title có màu Primary đó ông, color làm gì nhỉ, tạo component mới thôi, tham khảo fe-dev--native

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/atoms/text/Paragraph.tsx
> +  return <Text style={smallParagraphStyles}>{children}</Text>;
??? chuyển nhánh qua fe-dev--native sẽ có theme

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/atoms/svg/NumberPhone.tsx
> +interface NumberPhoneProps {
type phoneNumberProps

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/atoms/svg/NumberPhone.tsx
> +function NumberPhone({ width, height }: NumberPhoneProps) {
Tạo 1 component SVG có các tuỳ chọn muón svg hình nào, google hay facebook hay phone, width height ra sao, giảm được số lượng file và component

2024-02-21 05:52 UTC, bluehairmylove2014 commented on libs/presentational/src/native/atoms/button/Button.tsx
> +const Button = ({
Một button có quá nhiều cấu hình và tuỳ chọn, độ bao phủ và phức tạp lớn => Khả năng tái sử dụng của cả team là rất thấp, thay vào đó, tạo các component button đơn giản, đặt tên dễ phân biệt và tham số đầu vào đơn giản. Ví dụ làm những cái nút để cho màn hình intro login, có các icon và text, rộng full thì có thể tạo component ExpandSvgIconButton, tham số truyền vào gồm 2 cái, icon gì và title của button là gì, hết. Người khác dòm vô thì dễ hiểu và dễ sài lại hơn

2024-02-23 15:11 UTC, TanKaka123 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +          <SmallParagraph fontWeight="bold">Điều khoản dịch vụ</SmallParagraph>{' '}
chưa biết chuyển đi đâu với cũng chưa có url

2024-02-23 15:12 UTC, TanKaka123 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +          <SmallParagraph fontWeight="bold">Điều khoản dịch vụ</SmallParagraph>{' '}
cái này để update sau cũng được ( nếu giờ chưa có )

2024-02-23 15:20 UTC, TanKaka123 commented on libs/presentational/src/native/atoms/text/Title.tsx
> +const PrimaryTitle = ({ children, color }: { children: React.ReactNode, color?: string }) => (
muốn màu khác thì sao nhỉ? Ở intro k dùng title primaryColor dc. Với trường hợp k param color thì cũng default là Primary

2024-02-23 15:22 UTC, TanKaka123 commented on libs/presentational/src/native/atoms/text/Paragraph.tsx
> +  return <Text style={smallParagraphStyles}>{children}</Text>;
có theme thì sao nhỉ? chưa hiểu

2024-02-23 15:39 UTC, TanKaka123 commented on libs/presentational/src/native/atoms/svg/NumberPhone.tsx
> +function NumberPhone({ width, height }: NumberPhoneProps) {
Svg là image thì nó dài lắm, trường hợp có 30 cái svg là tìm k nổi luôn
Giảm số lượng file mà dồn hết zo 1 file nó cũng k có tác dụng gì đâu :V

2024-02-23 16:40 UTC, TanKaka123 commented on libs/presentational/src/native/atoms/button/Button.tsx
> +const Button = ({
tui nghĩ nhưng button chung chung nên tạo 1 factory để dùng thay vì mỗi button mỗi tạo 1 component với tên khác nhau. Những button đặc biệt thì mới nên tạo 1 file với component riêng, chứ 1 app cả chục cái button thì tạo chục file thì lạ quá. Cái button chung thì factory luôn

2024-02-23 16:44 UTC, TanKaka123 commented on libs/presentational/src/native/organisms/Header.tsx
> +      uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/United-kingdom_flag_icon_round.svg/1024px-United-kingdom_flag_icon_round.svg.png',
cái thằng này nó bắt buộc dùng url cho SelectCountry. Nếu trường hợp url die thì nó k display ( k raise error hay warning vì nó block rồi). Đang dùng image của cdn.countryflags.com ( khá uy tính ). Trường hợp solution này không được accept thì tui đổi sang lib khác

2024-02-27 00:32 UTC, closed without merging