intro customer mobile screen
bluehairmylove2014/detoi.vn pull request #32
Opened 2024-02-27 01:00 UTC by TanKaka123

2024-02-27 12:56 UTC, bluehairmylove2014 requested changes

2024-02-27 12:56 UTC, bluehairmylove2014 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +        <Paragraph color="black">Ứng dụng hỗ trợ mọi dịch vụ bạn cần</Paragraph>
Blackparagraph

2024-02-27 12:56 UTC, bluehairmylove2014 commented on apps/customer-mobile/src/screens/intro/index.tsx
> +          <Paragraph fontWeight="bold">Điều khoản dịch vụ</Paragraph> và{' '}
Tạo component Link, href = '#'

2024-02-28 14:20 UTC, TanKaka123 commented on libs/presentational/src/native/organisms/header/Header.tsx
> +      uri: 'https://cdn.countryflags.com/thumbs/vietnam/flag-square-250.png',
hiện tại lib đó chỉ dùng dc url bên ngoài, có 2 solution, 1 là down img về và upload lên cloud detoi, 2 là dùng lib khác

2024-02-29 16:26 UTC, merged